# Generated by Django 5.2.3 on 2025-06-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_year_built'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='backyard',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='front_yard',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='interior',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
