# Generated by Django 5.2.3 on 2025-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_backyard_property_front_yard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.CharField(default='No description available', max_length=150),
        ),
    ]
