# Generated by Django 5.2.3 on 2025-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_description_property_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='full_description',
            field=models.TextField(default='No description available', max_length=150),
        ),
    ]
