# Generated by Django 5.2.3 on 2025-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='full_description',
            field=models.TextField(default='No description available', max_length=600),
        ),
    ]
